# Cvičení 1

Začnemě opakováním základů programovacího jazyka Python, tzn. tvorbou a prací s proměnnými, cykly (`for`) a podmínkami (`if, else, elif`). Následně se zaměříme na knihovnu Numpy, která slouží k práci vektory a maticemi.

## Práce s buňkami v notebooku

Připomeňme, že buňku (cell) s kódem v Jupyter Notebooku můžeme spustit těmito příkazy:
- `Ctrl + Enter` - spustí daný řádek kódu
- `Shift + Enter` - spustí daný řádek kódu a přejde na další řádek
- `Alt + Enter` - spustí daný řádek kódu a vytvoří nový řádek pod ním

Další možnost je využít tlačítko `Execute cell` vlevo nahoře od buňky.

## Základní aritmetické operace

Notebook (resp. Python interpret samotný) můžeme využít jako kalkulátor k základním výpočtům. Výsledky nemusíme ukládat do proměnných. Zkuste spustit následující buňky.

In [2]:
1+1

2

In [3]:
10*(2+3)

50

In [4]:
3*sin(3)

NameError: name 'sin' is not defined

Předchozí buňku nebylo možné spustit. Abychom mohli využívat pokročilejší matematické operace, musíme importovat příslušnou knihovnu (v tomto případě math nebo numpy). Projděte si a spusťte následující buňky.

In [5]:
import math
3*math.sin(3)           # Musíme volat s návzem knihovny "math."

0.4233600241796016

In [ ]:
from math import sin
3*sin(math.pi)          # sin můžeme volat i bez návzu knihovny, před konstantu pi musíme stále  napsat "math."

**Pozor**: Následující přístup sice funguje a načte vše z knihovny `math`, ale je považován za **špatný zvyk**. Nevíte, co vše se z knihovny načetlo, názvy importovaných proměnných a funkcí mohou **kolidovat** s vašimi názvy nebo s funkcemi načtenými z jiných knihoven.

**Nevyužívejte**, pokud to není nezbytně nutné. 

In [6]:
from math import *
3*acos(sin(pi))         # Načte se vše z knihovny math, vše lze volat bez počátečního "math."

4.71238898038469

## Proměnné 

Proměnné definujeme pomocí znaku `=`. Typ proměnné není nutné specifikovat (Python je dynamicky typovaný jazyk, typ proměnné určí interpret jazyka automaticky).

In [7]:
a = 5
b = math.pi
c = "Hello world"

print(a)
print(b)
print(c)

5
3.141592653589793
Hello world


Jakého typu je daná proměnná můžeme zjistit pomocí příkazu `type`.

In [8]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


## `for` cyklus

Pro cyklus s předem daným počtem iterací využíváme příkaz `for`. Základní použití je v kombinaci s příkazem `range`, pomocí kterého vytvoříme tzv. iterovatelný objekt:

- `range(n)` - vytvoří iterovatelný objekt, který obsahuje čísla od 0 do n-1
- `range(m, n)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1
- `range(m, n, k)` - vytvoří iterovatelný objekt, který obsahuje čísla od m do n-1 s krokem k

Následující kód iteruje od 0 do 5 a vypíše současnou hodnotu `i`.

In [9]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [10]:
# UKOL: Doplňte kód, který vypíše sudá čísla od 2 do 10 (včetně):
for x in range(2, 11, 2):
    print(x)

2
4
6
8
10


## Podmínky

K vytváření podmíněných bloků kódu slouží příkazy `if`, `else`, `elif`.

K porovnávání mezi hodnotami používáme operátory `==`, `>=`, `<=`, `>`, `<`, `!=`

In [11]:
x = 0.5

if (abs(x) <= 1):
    y = math.acos(x)
    print("acos(x) = {}".format(y))
else:
    print("Hodnota proměnné je mimo definiční obor funkce.")

acos(x) = 1.0471975511965979


In [12]:
""" 
UKOL: Doplňte následující kód tak, aby 
1) smyčka iterovala od 1 do 20 včetně
2) vypsal aktuální i
3) pokud je aktuální i sudé, vypsal na dalším řádku "Sudé číslo"
4) pokud je aktuální i liché, vypsal na dalším řádku "Liché číslo"

K určení toho, zda je číslo sudé, potřebujete modulo operátor % - zbytek po 
celočíselném deleni. (zbytek = delenec % delitel) 

"""

for i in range(1, 21):
    print(i, "\n", "Sudé" if i % 2 == 0 else "Liché", " číslo", sep="")

1
Liché číslo
2
Sudé číslo
3
Liché číslo
4
Sudé číslo
5
Liché číslo
6
Sudé číslo
7
Liché číslo
8
Sudé číslo
9
Liché číslo
10
Sudé číslo
11
Liché číslo
12
Sudé číslo
13
Liché číslo
14
Sudé číslo
15
Liché číslo
16
Sudé číslo
17
Liché číslo
18
Sudé číslo
19
Liché číslo
20
Sudé číslo


## Knihovna NumPy

V tomto kurzu budeme pracovat hlavně s knihovnou `NumPy`, základní knihovnou pro vědecké výpočty v Pythonu. Umožňuje nám manipulaci s vektory a maticemi, implementuje operace mezi nimi či maticové rozklady.

In [13]:
import numpy as np      #  np je běžně využívaná zkratka pro numpy

Matice a vektory můžeme vytvořit např. pomocí:

- `np.array()` - vytvoří vektor/matici z listu
- `np.zeros()` - vytvoří vektor/matici o daných rozměrech, která je naplněna nulami
- `np.ones()` - vytvoří vektor/matici o daných rozměrech, která je naplněna jedničkami
- `np.linspace()` - vytvoří vektor o daných rozměrech, který obsahuje čísla od m do n-1 s krokem k
- `np.eye()` - vytvoří jednotkovou matici o daných rozměrech
- `np.random.rand()` - vytvoří vektor/matici o daných rozměrech, která je naplněna náhodnými čísly z intervalu [0, 1)

(Vzpomeňte si, že dokumentaci k jednotlivým funkcím s detailnějším popisem můžete zavolat pomocí příkazu `help`, např. `help(np.linspace)`)

Příklady použití:

In [14]:
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) 

[[1 2 3]
 [4 5 6]]


In [16]:
e = np.ones(4)
print(e)

[1. 1. 1. 1.]


In [17]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
"""
ÚKOL: 
1) Vytvořte matici A samých nul, která má 4 řádky a 3 sloupce.
2) Vytvořte náhodný vektor b o čtyřech prvcích.
3) Vytvořte vektor v obsahující 10 čísel rovnoměrně rozmístěných mezi 0 a 5 včetně.
"""

A = np.zeros((4, 3))
b = np.random.randint(0, 10, size=(4))
v = np.linspace(0, 5, 10)
print(A, b, v, sep="\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[2 4 0 4]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Chceme-li přistupovat k prvkům matice či vektoru v NumPy, využíváme hranaté závorky `[]` a indexujeme od nuly. 

In [34]:
b = np.array([0, 1, 2, 3, 4])
print(b)

x = b[1]        # druhý prvek vektoru b
print(x)

x = b[0:3]      # prvky na pozicích 0 až 2
print(x)

x = b[0:5:2]    # každý druhý prvek vektoru, (zopakujme syntaxi: x = b[start:end+1:krok])
print(x)

x = b[[1, 3]]   # prvky na pozicích 1, 3
print(x)

x = b[-1]       # můžeme indexovat odzadu, indexem -1 získáme poslední prvek, -2 předposlední, atd.
print(x)

[0 1 2 3 4]
1
[0 1 2]
[0 2 4]
[1 3]
4


In [35]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A)

a = A[0, 0]         # prvek na pozici (0, 0)
print(a)

a = A[1, 3]         # prvek na pozici (1, 3)
print(a)

B = A[0, 1:3]       # prvky na prvním řádku v druhém až třetím sloupci (v řeči indexů - na 0. řádku a 1. až 3. sloupci bez 3. sloupce)
print(B)

[[1 2 3 4]
 [5 6 7 8]]
1
8
[2 3]


In [36]:
"""
ÚKOL: 
1) Vytvořte náhodnou matici o rozměrech 5x5.
2) Do vektoru v uložte poslední řádek matice, vektor vytiskněte.
3) Do vektoru u uložte prvky na druhém řádku matice v prvním a posledním sloupci, vytiskněte.
"""

A = np.random.randint(0, 10, size=(5, 5))
print(A)
v = A[-1]
print(v)
u = A[1, [0, -1]]
print(u)

[[0 3 6 3 6]
 [9 3 2 1 6]
 [4 1 3 8 1]
 [7 0 2 5 9]
 [4 6 9 4 7]]
[4 6 9 4 7]
[9 6]


Vektory v NumPy mohou být reprezentovány jako 
1) 1D pole, např. `x = np.array([1, 2, 3])` nebo `y = ones(6)`
2) 2D pole ve formě řádku, např. `x = np.array([[1, 2, 3]])` nebo `y = np.zeros((1, 4))`
3) 2D pole ve formě sloupce, např. `x = np.array([[1], [2], [3]])`, `y = np.zeros((5, 1))` nebo `y = np.array([[1, 2, 3]]).T`

Vzhledem k tomu, že vektory budeme využívat zejména k účelům algoritmů lineární algebry, doporučuji vám je rovnou vytvářet ve 2D formě jako řádek nebo sloupec. Další možnost je vytvořit 1D pole a to _reshapovat_ na správné rozměry.

In [38]:
x = np.array([1, 2, 3])     # vytvoří 1D pole (ani řádek, ani sloupec)
x = x.reshape(3, 1)         # konvertuje x na 2D sloupcový vektor
print(x)
print(np.shape(x))          # vytiskne rozměry x 

print("---------------------")

y = np.array([1, 2, 3]).T   # vytvoříme řádkový vektor a transponujeme jej
print(y)
print(np.shape(y))

[[1]
 [2]
 [3]]
(3, 1)
---------------------
[1 2 3]
(3,)


In [39]:
"""
ÚKOL: 
1) Vytvořte náhodný sloupcový vektor x délky 5 a náhodný řádkový vektor y délky 5
2) Pomocí vhodných funkcí z knihovny NumPy určete 
    - normu vektoru x
    - skalární součin vektoru y s vektorem x
    - součet vektoru x s transpozicí vektoru y
"""

x = np.random.randint(-9, 10, size=(5, 1))
y = np.random.randint(-9, 10, size=(1, 5))

print(np.linalg.norm(x))
print(y @ x)
print(x + y.T)

13.784048752090222
[[27]]
[[  0]
 [  5]
 [-10]
 [ -7]
 [ 17]]


In [40]:
"""
ÚKOL:
Vypočítejte nyní normu vektoru x a skalární součin y*x "manuálně" pomocí cyklů for.
"""

norma = 0
for n in x:
    norma += n**2
norma = np.sqrt(norma)
print(norma)

skal_soucin = 0
for i, j in zip(y.T, x):
    skal_soucin += i * j
print(skal_soucin)


[13.78404875]
[27]


NumPy podporuje také samozřejmě také násobení matice s vektorem či matice s maticí. K tomu lze využít funkci `matmul` nebo operátor `@`.

In [41]:
A = np.ones((3, 3))
x = np.array([0, 1, 2])
x = x.reshape(3, 1)         # převedeme x na sloupcový vektor abychom jím mohli násobit matici zprava

y = np.matmul(A, x)         # násobení pomocí matmul
print(y)

z = A @ x                   # násobení pomocí operátoru @
print(y)

B = np.random.rand(3, 3)
C = np.matmul(A, B)
print(C)

[[3.]
 [3.]
 [3.]]
[[3.]
 [3.]
 [3.]]
[[0.89206511 2.0597051  1.59190391]
 [0.89206511 2.0597051  1.59190391]
 [0.89206511 2.0597051  1.59190391]]


In [43]:
"""
ÚKOL:
Do funkce muj_matvec implementujte vaši verzi násobení matice s vektorem.
Využijte dvě vnořené smyčky for. Na vstupu bude matice A a sloupcový vektor x 
odpovídající délky. Funkce bude vracet vektor y = Ax.
"""


def muj_matvec(A, x):
    # tuple unpacking, m obsahuje počet řádků, n počet sloupců matice A
    m, n = np.shape(A)
    y = np.zeros((m, 1))
    for i in range(m):
        for j in range(n):
            y[i] += A[i, j] * x[j]

    return y


In [48]:
# Zde si voláním funkce ověřte, zda funguje správně:

A = np.random.rand(3, 4)
x = np.random.rand(4, 1)
y = muj_matvec(A, x)
print(y)        # vytiskneme výsledek z vaší funkce

yy = A @ x
print(yy)       # porovnejte s voláním zabudované numpy funkce

[[0.44062796]
 [1.26872419]
 [1.60003487]]
[[0.44062796]
 [1.26872419]
 [1.60003487]]


In [53]:
# Porovnáme časy výpočtu pomocí vaší funkce a zabudované numpy funkce

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci 
%time y = muj_matvec(A, x)

# otestujeme zabudovanou implementaci
%time yy = A @ x

CPU times: user 6.95 ms, sys: 12.1 ms, total: 19 ms
Wall time: 5.11 ms
CPU times: user 143 µs, sys: 1e+03 ns, total: 144 µs
Wall time: 57.5 µs


`Dovolil jsem si vyměnit Python kód za Jupyter Magics kvůli přehlednosti. Dále jsem potřeboval na svém počítači přepsat dvoutisíce na dvacítky, jinak bych se výsledku nedočkal.`

Implementujte nyní násobení matice-vektor na základě předpisu $$A\mathbf{x} = \sum_{i=1}^n x_i \mathbf{a}_i,$$
kde $\mathbf{a}_i$ je $i$-tý sloupec matice $A$ a $x_i$ je příslušný prvek vektoru $\mathbf{x}$.

Nápověda: budete-li chtít vytáhnout sloupec matice pomocí příkazu `A[:, i]`, NumPy redukuje dimenzi a vrátí 1D vektor. Pro získání 2D sloupcového vektoru je třeba zavolat `A[:, [i]]`.

In [54]:
# ÚKOL: Doplňte implementaci.

def muj_matvec_v2(A, x):
    m, n = A.shape
    y = np.zeros((m, 1))
    for i in range(n):
        y += x[i] * A[:, [i]]
    return y

muj_matvec_v2(A, x)

array([[4.85066946],
       [4.13526665],
       [4.39149362],
       [5.00557273],
       [6.03582754],
       [4.75633658],
       [4.34428547],
       [4.4987934 ],
       [3.99665248],
       [4.83068081],
       [4.48180242],
       [4.53271975],
       [4.88145932],
       [3.09921592],
       [4.28076359],
       [5.00607936],
       [3.74969464],
       [3.77844957],
       [4.04698506],
       [2.89170935]])

In [87]:
# Ověřte funkčnost :

A = np.random.rand(3, 4)
x = np.random.rand(4, 1)

y = muj_matvec(A, x)
print(y)

yy = muj_matvec_v2(A, x)
print(yy)

yyy = A @ x
print(yyy)

[[1.65795682]
 [0.96839684]
 [0.61926407]]
[[1.65795682]
 [0.96839684]
 [0.61926407]]
[[1.65795682]
 [0.96839684]
 [0.61926407]]


In [57]:
# Otestujte na stejně velké matici jako vaši předchozí verzi a porovnejte výpočetní časy. 
# Liší se časy významně? Pokud ano, pokuste se zdůvodnit proč.

A = np.random.rand(2000, 2000)
x = np.random.rand(2000, 1)

# otestujeme vaši implementaci
%time y = muj_matvec_v2(A, x)

# otestujeme zabudovanou implementaci
%time yy = A @ x

CPU times: user 48.4 ms, sys: 0 ns, total: 48.4 ms
Wall time: 48.4 ms
CPU times: user 5.18 ms, sys: 4 ms, total: 9.17 ms
Wall time: 3.13 ms


In [99]:
# Bonus: Pokuste se implementovat funkci mat_mat, která bude násobit dvě matice. 
# Porovnejte výkon s funkcí z knihovny NumPy.
def mat_mat(A, B):
    assert(A.shape[1] == B.shape[0])
    m, n = A.shape[0], B.shape[1]
    C = np.zeros((m, n))
    for i in range(n):
        C[:, i] = muj_matvec_v2(A, B[:, i]).ravel()

In [103]:
A = np.random.rand(2000, 2000)
B = np.random.rand(2000, 2000)

%time y = mat_mat(A, B)

%time yy = A @ B

CPU times: user 1min 24s, sys: 78.1 ms, total: 1min 24s
Wall time: 1min 24s
CPU times: user 1.62 s, sys: 39.9 ms, total: 1.66 s
Wall time: 434 ms
